
package igu;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Cancion;
import modelo.Playlist;


public class Vista extends javax.swing.JFrame {
    private ArrayList<Cancion> canciones = new ArrayList<>();
    private ArrayList<Playlist> playlists = new ArrayList<>(); 
    
    /** Creates new form Vista */
    public Vista() {
        initComponents();
        iniciarEstilos();
        iniciarAcciones();
    }
    private void iniciarAcciones(){
        listaCanciones_Todo.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int index = listaCanciones_Todo.locationToIndex(e.getPoint());
                if (index != -1) {
                    String nombreCancion = listaCanciones_Todo.getModel().getElementAt(index);
                    textoTituloCancion.setText(nombreCancion);
                }
            }
        });
    }
    private void iniciarEstilos(){
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestañas = new javax.swing.JTabbedPane();
        pestañaCanciones = new javax.swing.JPanel();
        separador = new javax.swing.JSeparator();
        textoListaCanciones = new javax.swing.JLabel();
        campoBuscarCancion = new javax.swing.JTextField();
        textoTituloCancion = new javax.swing.JLabel();
        botonStop = new javax.swing.JButton();
        botonStart = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        pestañasPlaylist = new javax.swing.JTabbedPane();
        panelScroll_Todo = new javax.swing.JScrollPane();
        listaCanciones_Todo = new javax.swing.JList<>();
        pestañaPlaylist = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolPlaylist = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoListaCanciones.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textoListaCanciones.setText("Lista Canciones");

        campoBuscarCancion.setForeground(new java.awt.Color(153, 153, 153));
        campoBuscarCancion.setText("buscar");
        campoBuscarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarCancionActionPerformed(evt);
            }
        });

        textoTituloCancion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoTituloCancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTituloCancion.setText("Titulo:");
        textoTituloCancion.setMaximumSize(new java.awt.Dimension(189, 32));
        textoTituloCancion.setMinimumSize(new java.awt.Dimension(189, 32));

        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pausaOriginal.png"))); // NOI18N
        botonStop.setContentAreaFilled(false);
        botonStop.setMaximumSize(new java.awt.Dimension(32, 32));
        botonStop.setMinimumSize(new java.awt.Dimension(32, 32));
        botonStop.setPreferredSize(new java.awt.Dimension(32, 32));
        botonStop.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pausaPresionado.png"))); // NOI18N
        botonStop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pausaAdentro.png"))); // NOI18N

        botonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reproducirOriginal.png"))); // NOI18N
        botonStart.setContentAreaFilled(false);
        botonStart.setMaximumSize(new java.awt.Dimension(32, 32));
        botonStart.setMinimumSize(new java.awt.Dimension(32, 32));
        botonStart.setPreferredSize(new java.awt.Dimension(32, 32));
        botonStart.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reproducirPresionado.png"))); // NOI18N
        botonStart.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reproducirAdentro.png"))); // NOI18N
        botonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStartActionPerformed(evt);
            }
        });

        botonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reiniciarOriginal.png"))); // NOI18N
        botonReset.setContentAreaFilled(false);
        botonReset.setMaximumSize(new java.awt.Dimension(32, 32));
        botonReset.setMinimumSize(new java.awt.Dimension(32, 32));
        botonReset.setPreferredSize(new java.awt.Dimension(32, 32));
        botonReset.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reiniciarPresionado.png"))); // NOI18N
        botonReset.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reiniciarAdentro.png"))); // NOI18N

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busquedaOriginal.png"))); // NOI18N
        botonBuscar.setContentAreaFilled(false);
        botonBuscar.setMaximumSize(new java.awt.Dimension(32, 32));
        botonBuscar.setMinimumSize(new java.awt.Dimension(32, 32));
        botonBuscar.setPreferredSize(new java.awt.Dimension(32, 32));
        botonBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busquedaPresionado.png"))); // NOI18N
        botonBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busquedaAdentro.png"))); // NOI18N
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        listaCanciones_Todo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Roto", "locura", "mesi", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelScroll_Todo.setViewportView(listaCanciones_Todo);

        pestañasPlaylist.addTab("Todo", panelScroll_Todo);

        javax.swing.GroupLayout pestañaCancionesLayout = new javax.swing.GroupLayout(pestañaCanciones);
        pestañaCanciones.setLayout(pestañaCancionesLayout);
        pestañaCancionesLayout.setHorizontalGroup(
            pestañaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestañaCancionesLayout.createSequentialGroup()
                        .addComponent(textoListaCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBuscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separador)
                    .addGroup(pestañaCancionesLayout.createSequentialGroup()
                        .addComponent(textoTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pestañasPlaylist, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pestañaCancionesLayout.setVerticalGroup(
            pestañaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pestañaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textoListaCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(campoBuscarCancion))
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pestañasPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pestañaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pestañas.addTab("Canciones", pestañaCanciones);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLAYLIST");

        jScrollPane1.setViewportView(arbolPlaylist);

        javax.swing.GroupLayout pestañaPlaylistLayout = new javax.swing.GroupLayout(pestañaPlaylist);
        pestañaPlaylist.setLayout(pestañaPlaylistLayout);
        pestañaPlaylistLayout.setHorizontalGroup(
            pestañaPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestañaPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );
        pestañaPlaylistLayout.setVerticalGroup(
            pestañaPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestañas.addTab("PlayLists", pestañaPlaylist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonStartActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoBuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscarCancionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolPlaylist;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonReset;
    private javax.swing.JButton botonStart;
    private javax.swing.JButton botonStop;
    private javax.swing.JTextField campoBuscarCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCanciones_Todo;
    private javax.swing.JScrollPane panelScroll_Todo;
    private javax.swing.JPanel pestañaCanciones;
    private javax.swing.JPanel pestañaPlaylist;
    private javax.swing.JTabbedPane pestañas;
    private javax.swing.JTabbedPane pestañasPlaylist;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel textoListaCanciones;
    private javax.swing.JLabel textoTituloCancion;
    // End of variables declaration//GEN-END:variables

}
